// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72ZdAqR-IEmxBeo-3ls64X2ouVhLcNUE',
    appId: '1:958370146112:web:3ca7c66b6b5d34d2eb7ca5',
    messagingSenderId: '958370146112',
    projectId: 'quizmaker-78191',
    authDomain: 'quizmaker-78191.firebaseapp.com',
    storageBucket: 'quizmaker-78191.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt9H5AhUC2LbgBvuWBJRrxs-lm7kr-uN4',
    appId: '1:958370146112:android:a7bed0625dc027c1eb7ca5',
    messagingSenderId: '958370146112',
    projectId: 'quizmaker-78191',
    storageBucket: 'quizmaker-78191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyUdBC98NM130xMOAH0tehVV16_xKC4A',
    appId: '1:958370146112:ios:b8055b8a98d9bf8eeb7ca5',
    messagingSenderId: '958370146112',
    projectId: 'quizmaker-78191',
    storageBucket: 'quizmaker-78191.appspot.com',
    iosClientId: '958370146112-c9k9hp1jd040kr44f0dg2i8gvmff1hfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyUdBC98NM130xMOAH0tehVV16_xKC4A',
    appId: '1:958370146112:ios:b8055b8a98d9bf8eeb7ca5',
    messagingSenderId: '958370146112',
    projectId: 'quizmaker-78191',
    storageBucket: 'quizmaker-78191.appspot.com',
    iosClientId: '958370146112-c9k9hp1jd040kr44f0dg2i8gvmff1hfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp2',
  );
}
